#pragma once
#include <iostream>
#include <string>
#include <WS2tcpip.h>
#include <Windows.h>
#include <WinSock2.h>
#include <locale>
#include <vector>
#include <unordered_map>
#include <algorithm>
#include <filesystem>
#include <queue>
#include <sstream>
#include "curses.h"
#include <thread>
#include <chrono>
#include <fstream>
#include <iomanip>
#include <optional>
#include <functional>
#include <iterator>
#pragma comment (lib, "ws2_32.lib")